### PR TITLE
Market Prediction - Hari Krishna Naralasetty 

### PR DESCRIPTION
**Pull request by hknaralasetty**
Hi, I have done the program with 56% accuracy. The model used is LTSM. Please check the ipynb for detailed observation. email: harikrishna2k@icloud.com

### CODE REVIEW

**Comment by fluidai** [comment]
@hknaralasetty we liked your submission - you would have received an email from people@fluid.ai with details for your final round

**Review by fluidai — CHANGES_REQUESTED** [review]
@hknaralasetty Can you please put this in a folder called LSTM and change the file name to lstm_approach.ipynb and resubmit for it to be added to the repo. Thanks

**Comment by hknaralasetty** [comment]
Of course, on it!

**Comment by sivasankarg17** [comment]
Hi 
My self Siva sankar, My Mail Id sivasankar.slm@gmail.com and alternative mail Id is sivauniso@gmail.com and my contact number is 7829611313
I work on BTC_USD
And i got accuracy of  56 using Logistic Regression.

**Pull request merged**
